-- begin OPTAPLANNER_PROCESS
alter table OPTAPLANNER_PROCESS add constraint FK_OPTAPLANNER_PROCESS_ON_COMPUTER foreign key (COMPUTER_ID) references OPTAPLANNER_COMPUTER(ID)^
alter table OPTAPLANNER_PROCESS add constraint FK_OPTAPLANNER_PROCESS_ON_CLOUD_BALANCE foreign key (CLOUD_BALANCE_ID) references OPTAPLANNER_CLOUD_BALANCE(ID)^
create index IDX_OPTAPLANNER_PROCESS_ON_COMPUTER on OPTAPLANNER_PROCESS (COMPUTER_ID)^
create index IDX_OPTAPLANNER_PROCESS_ON_CLOUD_BALANCE on OPTAPLANNER_PROCESS (CLOUD_BALANCE_ID)^
-- end OPTAPLANNER_PROCESS
-- begin OPTAPLANNER_COMPUTER
alter table OPTAPLANNER_COMPUTER add constraint FK_OPTAPLANNER_COMPUTER_ON_CLOUD_BALANCE foreign key (CLOUD_BALANCE_ID) references OPTAPLANNER_CLOUD_BALANCE(ID)^
create index IDX_OPTAPLANNER_COMPUTER_ON_CLOUD_BALANCE on OPTAPLANNER_COMPUTER (CLOUD_BALANCE_ID)^
-- end OPTAPLANNER_COMPUTER
